[project]
name = "aurora"
version = "0.1.0"
description = ""
authors = [
    {name = "jin.yang",email = "jin.yang@openpie.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "langfuse (>=3.8.1,<4.0.0)",
    "openai (>=2.6.1,<3.0.0)",
    "poetry-core (>=2.2.1,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.9.0"

