[project]
name = "aurora"
version = "0.1.0"
description = ""
authors = [
    {name = "jin.yang",email = "jin.yang@openpie.com"}
]
readme = "README.md"
requires-python = ">=3.11, <4.0"
dependencies = [
    "langfuse (>=3.9.0,<4.0.0)",
    "openai (>=2.7.1,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "black (>=25.9.0,<26.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "whisper (>=1.1.10,<2.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
